name: Generate and Publish SDK

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate OpenAPI schema
        env:
          DATABASE_URL: sqlite:///:memory:
        run: |
          python manage.py spectacular --file sdk/schema.yaml

  publish:
    runs-on: ubuntu-latest
    needs: generate-schema
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          cd sdk/typescript
          npm ci

      - name: Generate SDK
        run: |
          cd sdk/typescript
          npm run generate

      - name: Build SDK
        run: |
          cd sdk/typescript
          npm run build

      - name: Bump SDK version
        run: |
          cd sdk/typescript
          npm version patch -m "chore(release): %s [skip ci]"

      - name: Commit version bump
        run: |
          cd sdk/typescript
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore: bump SDK version" || echo "No changes to commit"
          git push --follow-tags
        continue-on-error: true

      - name: Publish SDK to npm
        run: |
          cd sdk/typescript
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_NTQ_ACCESS_TOKEN }}
